stages:
  - build
  - deploy

build-job:
  only:
    - main
  image: mcr.microsoft.com/dotnet/sdk:7.0
  stage: build
  tags:
    - main
  script:
    - dotnet build ./PmEngine.Core
    - dotnet pack ./PmEngine.Core
    - cd PmEngine.Core/bin/Debug/
    - ls
  dependencies: []

deploy-job:
  stage: deploy
  only:
    - main
  tags:
    - main
  script:
    - ls
